### ISSUE TITLE
Multi-packet source RCON is broken

### ISSUE THREAD

**Issue by faustoFF** [xPaw/PHP-Source-Query#43] opened 2015-02-19 22:02 UTC
Hello!

I have a small game hosting and yesterday after one day of testing on stage i am roll out new SourceQuery (2015.02.17) lib to all hosting instances (when game servers hosted). Reason to update SourceQuery is partial output returns by SourceQuery, issue #24.

How SourceQuery works on my hosting: usually main hosting website send HTTP requests to instances. This requests contains RCON cmd to execute locally on instance by using SourceQuery. When RCON-request complited, results goes back to hosting website.

Today i receive emerg alerts from Zabbix and found one of instance with almost 100% CPU utilization, Apache processes doing this. Restarting Apache sends instance back to normal. When investigating for reasons of this problem, i watch to Apache workers statistic in Zabbix and found absolutely abnormal situation with to much workers in states "Sending Reply". This workers stuck one by one for several hours up to 150 or more stuck workers, when for a long time ago count of "Sending Reply" workers not exceed 2-4 avg.

After several minutes after Apache restart i found again stuck workers one by one. In Apache error log i found much of errors like this:

[Thu Feb 19 21:44:10 2015] [error] [client _._._._] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/***/SourceQuery/SourceRcon.class.php on line 96

96 line points to:

$Buffer2 = FRead( $this->RconSocket, $Length );

I try to reproduce stuck by hands and create simple script which connect to server, set rcon password, execute rcon command, disconnect and echo results of rcon execution. I run this script by typing address to browser. RCON cmd 'stats' works fine on all testing game servers, results shows in browser instantly. But finaly on some servers (not all), i found that commands 'status' and 'sm plugins list', which stuck script execution, browser endlessly waiting for response. Each runing of script from browser create one stuck worker with "Sending Reply" status.

I try to set small set_time_limit() for script, trying to set small socket timeout by using stream_set_timeout() in Socket.class.php and SourceRcon.class.php - nothing helps, script, browser and Apache worker still stuck on 'sm plugins list'.

I am temporary back to old tested and trusted SourceQuery, and everything back to normal, nothing stuck, but again I have problem with partial RCON output, issue #24 :(

What is wrong with SourceQuery? I'm almost completely sure than problem in SourceQuery, in case with 'sm plugins list' it stuck on some servers whatever timeout (socket or script) was set, but old SourceQuery works good without stuck but partial.

If you need to addititional info I gladly will provide this!

Hope for your help!

**Comment by xPaw** [comment] 2015-02-20 08:05
What timeout did you specify when connecting? If the issue is on fread line, there is absolutely nothing that I can do.

**Comment by faustoFF** [comment] 2015-02-20 08:11
Trying default 3 sec, trying 1 sec, trying set timeout in microseconts like this stream_set_timeout($socket, 0, 100000) - still stuck. Something wrong with timeouts, they doesnt work in some cases when script stuck on latest SourceQuery, but works great at old SourceQuery.

**Comment by xPaw** [comment] 2015-02-20 08:12
That is weird. Have you tried a different server or host?

**Comment by faustoFF** [comment] 2015-02-20 08:19
Currently i am in process of moving game server (where stuck reproduced) to stage environment. I am going to detect exactly line of SourceQuery lib code when stuck happens. Stay tuned :)

**Comment by faustoFF** [comment] 2015-02-20 11:33
Ok, as expected problem reproduce locally on stage environment for RCON cmd 'sm plugins list'.

I tried to find part of code when stuck happens by adding to SourceQuery code lines which loging to the file to emulate kind of handmade debug.

Trace:

$SQ->Rcon('sm plugins list')
then enters

$this->Rcon->Command( $Command ) in SourceQuery.class.php
then enters

$this->Read( ); after line $this->Write( SourceQuery :: SERVERDATA_RESPONSE_VALUE ); in SourceRcon.class.php

then
while( $Remaining > 0 )
{
    $Buffer2 = FRead( $this->RconSocket, $Length );
    $Buffer .= $Buffer2;

    $Remaining -= StrLen( $Buffer2 );
}
in SourceRcon.class.php.

This cycle begins to run indefinitely (thats why i so scare while cycles :) ). Execution enters in while with $Remaining = 1869508007. FRead() starts an infinite number of times and all times except first time returns nothing (StrLen( $Buffer2 ) = 0 ), $Remaining keep in value 1869507989 for ever. Thats why while cycle is indefinitely, thats why PHP script never ends, thats why Apache worker stuck in 'Sending Reply' state.

Here the outputs of vars each iteration of while cycle:

2015-02-20 14:02:39 - Buffer2: '', Buffer: 'unceEx" (2.0.0) by Franc1sco franug, Mini and GoD-Tony
L 02/20/2015 - 14:02:39: rcon from "192.168.0.10:59514": command "sm plugins list"

', Remaining: '1869508007', Strlen($Buffer2): 18
2015-02-20 14:02:39 - Buffer2: '', Buffer: 'unceEx" (2.0.0) by Franc1sco franug, Mini and GoD-Tony
L 02/20/2015 - 14:02:38: rcon from "192.168.0.10:59513": command "sm plugins list"

', Remaining: '1869507989', Strlen($Buffer2): 0
2015-02-20 14:02:40 - Buffer2: '', Buffer: 'unceEx" (2.0.0) by Franc1sco franug, Mini and GoD-Tony
L 02/20/2015 - 14:02:39: rcon from "192.168.0.10:59514": command "sm plugins list"

', Remaining: '1869507989', Strlen($Buffer2): 0
2015-02-20 14:02:40 - Buffer2: '', Buffer: 'unceEx" (2.0.0) by Franc1sco franug, Mini and GoD-Tony
L 02/20/2015 - 14:02:38: rcon from "192.168.0.10:59513": command "sm plugins list"

', Remaining: '1869507989', Strlen($Buffer2): 0
2015-02-20 14:02:41 - Buffer2: '', Buffer: 'unceEx" (2.0.0) by Franc1sco franug, Mini and GoD-Tony
L 02/20/2015 - 14:02:39: rcon from "192.168.0.10:59514": command "sm plugins list"

', Remaining: '1869507989', Strlen($Buffer2): 0
2015-02-20 14:02:41 - Buffer2: '', Buffer: 'unceEx" (2.0.0) by Franc1sco franug, Mini and GoD-Tony
L 02/20/2015 - 14:02:38: rcon from "192.168.0.10:59513": command "sm plugins list"

', Remaining: '1869507989', Strlen($Buffer2): 0

stream_set_timeout() works fine end set timeouts between unsuccessful attempts to get anything from fread().

I can share for you game server build for testing by yourself.

**Comment by xPaw** [comment] 2015-02-20 11:37
The question is why remaining buffer length is so huge.

I will add a fix for infinite loop though.

**Comment by faustoFF** [comment] 2015-02-20 11:48
Ok. HLSW works fine for 'sm plugins list' for this game server, old SourceQuery works fine too, but returns partial (some of first lines of result). Latest SourceQuery stuck cause of huge $Remaining.

**Comment by xPaw** [comment] 2015-02-20 11:49
Yeah the issue happens due to split packets that source server sends, old version simply didn't do anything about it, and that's why it returns partial response.

I'm trying to figure out a fix for this.

**Comment by faustoFF** [comment] 2015-02-20 12:01
Thank you!

**Comment by xPaw** [comment] 2015-02-20 12:34
I've fixed multi packet response reading, however there is one issue that I cannot figure out. After reading multi responses, it is not possible to read response of another command for some reason.

**Comment by faustoFF** [comment] 2015-02-20 13:41
I think its ok for me, because i use SourceQuery objects in 'born to die' style, when connect, execute something disconnect and return result. Each SQ object executes only one method from Rcon, Ping, GetInfo, GetPlayers, GetRules, SetRconPassword. In this use case a have no problems with "not possible to read response of another" issue, right?

P.S.: i checked 'sm plugins list' for new version of SourceQuery and it works fine, big thanks. But issue with "not possible to read response of another command" looks strange :)

**Comment by xPaw** [comment] 2015-02-20 13:42
I`ll leave the issue open, so I can take a look at it another time.

**Closed** 2017-12-26 16:27 UTC
Labels: bug
